app/blueprints/predicao/predicao_blueprint.py
from flask import Blueprint, flash, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from db import db
from werkzeug.utils import secure_filename
import os
from .processamento import gerar_df_pred, gerar_importancia, grupos_pred, processa_modelo
import joblib
from models import Documentos
import pandas as pd

predicao_bp = Blueprint('predicao', __name__, template_folder='templates', url_prefix='/predicao')

ALLOWED_EXTENSIONS = set(['csv'])
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@predicao_bp.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    if request.method == 'POST':
        if 'file' not in request.files:
            flash('No file part')
            return 'error'
        file = request.files['file']
        if file.filename == '':
            flash('No selected file')
            return "weee"
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            filename = f"{current_user.id}_{filename}"

            upload_folder = os.path.join('app', 'static', 'uploads', 'user', 'original')
            os.makedirs(upload_folder, exist_ok=True)  # Garante que o diretório existe
            file_path = os.path.join(upload_folder, filename)
            file.save(file_path)
            new_filename = filename.split('.csv', 1)[0]

            existing_doc = Documentos.query.filter_by(nome_documento=new_filename, user_id=current_user.id).first()
            if existing_doc:
                flash('Arquivo já existe')
                return 'error'
            uploadDoc = Documentos(
                user_id=current_user.id,
                caminho_origem=file_path,
                nome_documento=new_filename
            )
            db.session.add(uploadDoc)
            db.session.commit()

            return redirect(url_for('predicao.views', id=uploadDoc.id)) 
        # if not ALLOWED_EXTENSIONS, return 'error'
        return 'error'
    #GET
    return render_template('upload.html')

@predicao_bp.route('/delete/<int:id>', methods=['POST'])
@login_required
def delete(id):
    doc = db.session.query(Documentos).filter_by(id=id).first()
    if not doc or doc.user_id != current_user.id:
        flash('Documento não encontrado ou acesso negado.')
        return redirect(url_for('home'))

    # Remove arquivos associados
    if doc.caminho_pred and os.path.exists(doc.caminho_pred):
        os.remove(doc.caminho_pred)
    if doc.caminho_grupos and os.path.exists(doc.caminho_grupos):
        os.remove(doc.caminho_grupos)
    if doc.caminho_origem and os.path.exists(doc.caminho_origem):
        os.remove(doc.caminho_origem)

    # Remove gráficos se existirem
    nome_base = doc.nome_documento
    grafico_Importancia_path = os.path.join('app', 'static', 'uploads', 'sys', 'graphs', f'{nome_base}_importante.png')
    grafico_Risco_path = os.path.join('app', 'static', 'uploads', 'sys', 'graphs', f'{nome_base}_riscos.png')
    if os.path.exists(grafico_Importancia_path):
        os.remove(grafico_Importancia_path)
    if os.path.exists(grafico_Risco_path):
        os.remove(grafico_Risco_path)

    db.session.delete(doc)
    db.session.commit()
    flash('Documento deletado com sucesso.')
    return redirect(url_for('home'))

@predicao_bp.route('/view/<int:id>', methods=['GET', 'POST'])
@login_required
def views(id):
    doc = db.session.query(Documentos).filter_by(id=id).first()
    caminho = doc.caminho_origem
    nome = doc.nome_documento.split('.csv', 1)[0]
    if not doc or doc.user_id != current_user.id:
        return 'Documentos não encontrado ou você não tem autorização para acessa-lo', 404
    predito = doc.caminho_pred
    risco = doc.caminho_grupos
    if request.method == 'POST':

        if predito or risco:
            if os.path.exists(predito):
                os.remove(predito)
            if os.path.exists(risco):
                os.remove(risco)
            nome_base = nome
            grafico_Importancia_path = os.path.join('app', 'static', 'uploads', 'sys', 'graphs', f'{nome_base}_importante.png')
            grafico_Risco_path = os.path.join('app', 'static', 'uploads', 'sys', 'graphs', f'{nome_base}_riscos.png')
            if os.path.exists(grafico_Importancia_path):
                os.remove(grafico_Importancia_path)
            if os.path.exists(grafico_Risco_path):
                os.remove(grafico_Risco_path)

        input_df = pd.read_csv(caminho)
        modelo_path = os.path.join(
        os.path.dirname(__file__),
        'static', 'models', 'modelo_churn_rf_bank_telco.pkl')
        data = joblib.load(modelo_path)
        model = data['model']
        columns = data['columns']

        X = processa_modelo(input_df)

        preds = model.predict(X)
        probs = model.predict_proba(X)[:, 1]

        df_pred = gerar_df_pred(X, preds, probs)
        
        pred_path = os.path.join('app', 'static', 'uploads', 'sys', 'pred', f'{nome}_pred.csv')
        df_pred.to_csv(pred_path, index=False, encoding='utf-8')
        doc.caminho_pred = pred_path

        agrupado = grupos_pred(df_pred, nome)
        
        agrupado.columns = ['Sexo', 'Faixa Etária', 'Risco', 'Probabilidade Média', 'Total Clientes', 'Cancelamentos']
        agrupado['Probabilidade Média (%)'] = (agrupado['Probabilidade Média'] * 100).round(2)
        agrupado = agrupado.drop(columns=['Probabilidade Média'])

        # Salvar para download
        agrupado.to_csv(f'app/static/uploads/sys/pred/{nome}_grupos_risco.csv', index=False, encoding='utf-8')

        riscos_path = os.path.join('app', 'static', 'uploads', 'sys', 'pred', f'{nome}_grupos_risco.csv')
        doc.caminho_grupos = riscos_path

        db.session.commit()

        gerar_importancia(model, X, nome)
        return redirect(url_for('predicao.views', id=doc.id)) #redireciona para a view do documento
    #get
    print(nome)
    fig_importance = url_for('static', filename=f'uploads/sys/graphs/{nome}_importante.png')
    if fig_importance:
        return render_template('view.html', doc=doc, predito=predito, nome=nome, caminho=caminho, fig_importance=fig_importance)
    return render_template('view.html', doc=doc, nome=nome, predito=predito, caminho=caminho)
    

app/blueprints/predicao/templates/upload.html
{% extends 'header.html' %}

{% block content %}
<div class="container mt-5" style="max-width: 600px;">
    <h1 class="text-center mb-4 text-primary fw-bold">Envio de Documentos</h1>

    <form action="{{ url_for('predicao.upload') }}" method="POST" enctype="multipart/form-data" class="shadow p-4 rounded bg-white">
        <div class="mb-3">
            <label for="file" class="form-label">Escolha um documento (.csv)</label>
            <input type="file" class="form-control" id="file" name="file" required>
        </div>

        <div class="d-grid">
            <button type="submit" class="btn btn-primary rounded-pill">Enviar</button>
        </div>
    </form>

    <div class="mt-4 text-center">
        <a href="{{ url_for('home') }}" class="btn btn-outline-secondary rounded-pill px-4">Voltar</a>
    </div>
</div>
{% endblock %}

app/blueprints/predicao/templates/view.html
{% extends 'header.html' %}

{% block content %}
<div class="container mt-5" style="max-width: 800px;">
    <h1 class="text-center text-primary fw-bold mb-4">Detalhes do Documento</h1>

    <div class="shadow p-4 bg-white rounded">
        <h4 class="mb-3">Documento: <span class="text-dark">{{ nome.split('_', 1)[1].replace('_', ' ').replace('-', ' ') }}</span></h4>

        <div class="mb-4">
            <h5>Documento carregado:</h5>
            <a class="btn btn-outline-success rounded-pill w-100" 
               href="{{ url_for('static', filename='uploads/user/original/' ~ doc.nome_documento ~ '.csv')}}" 
               download>
                📎 Baixar arquivo original
            </a>
        </div>

        <div class="mb-4">
            <h5>Previsões:</h5>

            <div class="alert alert-info mb-4">
                <strong>Para gerar predições:</strong>
                <ul class="mb-2">
                    <li>
                        É recomendado que linhas de identificação sejam retiradas
                        O dataset <b>deve conter</b> a coluna de churn com um dos seguintes nomes:<br>
                        <span class="badge bg-primary text-light me-1">churn</span>
                        <span class="badge bg-primary text-light me-1">cancelado</span>
                        <span class="badge bg-primary text-light me-1">cancelou</span>
                        <span class="badge bg-primary text-light me-1">cancelamento</span>
                        <span class="badge bg-primary text-light me-1">saida</span>
                        <span class="badge bg-primary text-light">exited</span>
                    </li>
                    <li>
                        Para maior acurácia, colunas opcionais incluem:
                        <ul class="mt-1">
                            <li><span class="badge bg-secondary me-1">idade</span> <span class="badge bg-secondary me-1">age</span> <span class="badge bg-secondary">idade_cliente</span></li>
                            <li><span class="badge bg-secondary me-1">sexo</span> <span class="badge bg-secondary me-1">genero</span> <span class="badge bg-secondary">gender</span></li>
                            <li><span class="badge bg-secondary me-1">salario</span> <span class="badge bg-secondary">EstimatedSalary</span></li>
                            <li><span class="badge bg-secondary">mensalidade</span> <span class="badge bg-secondary">MonthlyCharges</span></li>
                            <li><span class="badge bg-secondary">tempo</span> <span class="badge bg-secondary">tenure</span></li>
                        </ul>
                    </li>
                </ul>
            </div>

            {% if not predito %}
                <p class="text-muted">Nenhuma predição disponível ainda.</p>
                <form method="post">
                    <button type="submit" class="btn btn-primary rounded-pill w-100">Prever</button>
                </form>
            {% else %}
                <div class="mb-3 d-flex gap-2">
                    <a class="btn btn-outline-success rounded-pill" href="{{ url_for('static', filename='uploads/sys/pred/' ~ nome ~ '_pred.csv') }}" download>
                        📊 Baixar predições
                    </a>
                    <a class="btn btn-outline-success rounded-pill" href="{{ url_for('static', filename='uploads/sys/pred/' ~ nome ~ '_grupos_risco.csv') }}" download>
                        📊 Baixar Grupos de Risco
                    </a>
                </div>
                <div class="row">
                    <form method="post" class="mb-4">
                        <button type="submit" class="btn btn-warning rounded-pill w-100">Refazer predições</button>
                    </form>
                </div>
                

                <h3>O que mais impacta seu churn</h3>
                    <img src="{{ fig_importance }}" alt="Media de Previsões" class="img-fluid mt-3">
            {% endif %}
        </div>

        <div class="text-center mt-4">
            <a href="{{ url_for('home') }}" class="btn btn-outline-secondary rounded-pill px-4">Voltar</a>
        </div>
        <div class="text-center mt-4">
            <form action="{{ url_for('predicao.delete', id=doc.id) }}" method="post">
                <button type="submit" class="btn btn-danger">Deletar Documento</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}